backup: general code clean-up
Simpler processing of command-line arguments / config file.  Now the
contents of the config file are treated exactly like command-line
arguments except for the section headers.

diff --git a/src/backup b/src/backup
--- a/src/backup
+++ b/src/backup
@@ -1,9 +1,29 @@
 #!/bin/sh
-# Make backups using find and tar.
 
 LC_ALL=C
 
 progname="$(basename "$0")"
+
+config_file="${XDG_CONFIG_HOME:-$HOME/.config}/backup.conf"
+
+tempf="$(mktemp)"		# to keep list of temporary files
+tempfile () {
+    mktemp | tee -a "$tempf"
+}
+
+clean_up () {
+    # remove temporary files
+    xargs -- rm -f < "$tempf"
+    rm -f "$tempf"
+}
+
+trap "clean_up" 0
+trap "exit 2" 1 2 3 15
+
+error () {
+    # write $1 to stderr
+    printf -- "$progname: %s\n" "$1" 1>&2
+}
 
 usage () {
     # write help message to stdout
@@ -13,85 +33,30 @@ Make backups using find and tar.
 
 Options:
 
- -i PATH              input directory
- -o PATH              output directory
- -r FILE              alternate config file
- -x                   do not read any config file
- -n NAME              backup name
-          --help      show this help and exit
+ -o PATH  --orig=PATH  backup directory
+ -d PATH  --dest=PATH  destination directory
+ -x                    do not read any config file
+ -n NAME  --name=NAME  backup name
+          --help       show this help and exit
 
-All arguments after "--"  are passed unchanged to find(1).
+Any argument after "--" is passed unchanged to find(1).
 
 $progname uses GNU find extensions.
 
 EOF
 }
 
-error () {			# $1=message
-    # write message to stderr
-    printf "$progname: %s\n" "$1" 1>&2
+conf () {
+    # write contents (minus header) of config file section $1 to stdout
+    if [ ! -e "$config" ]; then
+	return 1
+    fi
+    cat "$config_file" | sed '/^#/ d; /^\[.*\]$/ i\
+#' | awk -F'\n' -v RS='(^|\n)#\n' -v label="$1" \
+	 '$1 == "[" label "]" { print }' | tail -n +2
 }
 
-parse_command_line_args () {	# $1=getopt string with quoted args
-    # set variables from options, set rest_args to remaining args
-    eval set -- "$1"
-    while [ $# -gt 0 ]; do
-	case "$1" in
-	    --)
-		shift; break ;;
-	    --help)
-		usage; return 1 ;;
-	    -x)
-		x=true ;;
-	    -i|-o|-r|-n)
-		eval "${1#-}=\"\${2}\""
-		shift ;;
-	    *)
-		error "invalid parameter -- '${1#-}'"
-		return 2
-	esac
-	shift
-    done
-    test $# -gt 0 && rest_args="$(getopt -s sh -o '' -- "$@")"
-}
-
-parse_rcfile_args () {		# $1=getopt string
-    # set variables from options, set rest_args to remaining args
-    eval set -- "$1"
-    shift			# the first arg is -- generated by getopt
-    while [ $# -gt 0 ]; do
-	case "${1%%=*}" in
-	    --)
-		shift; break ;;
-	    i|o)
-		eval "${1%%=*}=\"\${1#*=}\"" ;;
-	    *)
-		error "invalid parameter in config file -- '${1%%=*}'"
-		return 1
-	esac
-	shift
-    done
-    test $# -gt 0 && rest_args="$(getopt -s sh -o '' -- "$@")"
-}
-
-get_rcfile_section () (		# $1=filename $2=section
-    # write section to stdout
-    cat "$1" | grep -v '^[[:space:]]*$\|^[[:space:]]*#.*' \
-	| while IFS= read line;
-    do
-	if [ -z "${line##[[]*[]]}" ]; then
-	    if [ "$line" = "[$2]" ]; then
-		insection=true
-	    else
-		insection=
-	    fi
-	elif [ -n "$insection" ]; then
-	    printf '%s\n' "$line"
-	fi
-    done
-)
-
-human_readable () (	# $1=amount in bytes
+human_friendly_units () (	# $1=amount in bytes
     # write string to stdout
     if [ $1 -lt 1024 ]; then
 	printf '%dB\n' $1
@@ -132,158 +97,131 @@ ask () {			# $1=question $2=options
     done
 }
 
-free_space () (		    # $1=file
-    # write free disk space in bytes to stdout
-    printf '%d\n' \
-	$((1024 * $(df -k -P "$1" | tail -n 1 | tr -s ' ' '\t' | cut -f 4)))
-)
-
-temporary_file () {
-    # make temp file, write filename to stdout
-    mktemp || \
-	{ error "could not create temporary file"; cleanup; return 1; }
-}
-
-find_previous_backup () (	# $1=basename $2=path
-    # write filename to stdout
-    # pattern: <NAME>.<NUMBER>.TAR.*
-    cd "$2" || { cleanup; return 1; }
-    ls -t -r | grep "^$1\.[0-9][0-9]*\.tar" | tail -n 1
-)
-
-current_backup () {		# $1=basename [$2=previous]
-    # write filename to stdout
-    if [ -n "$2" ]; then
-	num=$(printf '%s\n' "$(basename "$2")" | \
-	    sed "s/^$1\.\([0-9][0-9]*\)\.tar.*/\1/")
-    else
-	num=-1
-    fi
-    printf '%s.%04d.tar\n' "$1" $((1+$num))
-}
-
-cleanup () {
-    test -n "$files" && rm -f "$files"
-    test -n "$sizes" && rm -f "$sizes"
-}
-
-run_find () {			# $1=path $2=reference [args...]
-    # set files and sizes
-    files="$(temporary_file)" || return $?
-    sizes="$(temporary_file)" || return $?
-    (
-	path="$1"
-	reference="${2:+-newer "$2"}"
-	shift 2
-	find "$path" -xdev -depth ${reference} "$@" \
-	    -fprint0 "$files" -printf '%s\n' > "$sizes"
-    )
-}
-
-sum () (			# [$1=file]
-    # write total to stdout
-    while read number; do
-	total=$(($total+$number))
+set_pars () {
+    # set origin, destdir, noconf, name and restargs, from arg string $1
+    origin=
+    destdir=
+    noconf=
+    name=
+    help=
+    eval set -- "$1"
+    while [ $# -gt 0 ]; do
+	case "$1" in
+	    --help)
+		help=1;;
+	    -o|--orig)
+		shift; origin="$1";;
+	    -d|--dest)
+		shift; destdir="$1";;
+	    -x)
+		noconf=1;;
+	    -n|--name)
+		shift; name="$1";;
+	    *)
+		break;;
+	esac
+	shift
     done
-    printf "%d\n" ${total:-0}
-)
+    restargs="$(getopt -n "$progname" -s sh -o '' -- "$@")"
+}
 
-# parse command line
+# process command line arguments
+getopt -T 2> /dev/null
+if [ $? -ne 4 ]; then
+    error "unsupported version of getopt"
+    return 1
+fi
+opts="o:d:xn:"
+longopts="orig:,dest:,name:,help"
+args="$(getopt -n "$progname" -s sh -o $opts -l $longopts -- "$@")"
+[ $? -eq 0 ] || return 1
 
-i=
-o=
-r="$HOME/.config/backuprc"
-x=
-n=
-rest_args=
-opts="i:o:r:xn:"
-longopts="help"
+set_pars "$args" || exit
+eval set -- "$restargs"
+shift				# consume -- argument
 
-cl_args="$(getopt -n "$progname" -s sh -o $opts -l $longopts -- "$@")"
+[ -n "$help" ] && { usage; exit 0; }
+[ -z "$name" ] && { error "name required"; exit 1; }
 
-parse_command_line_args "$cl_args" || exit $(($?-1))
-test -z "$n" && { error "required argument missing -- 'n'"; exit 1; }
-
-if [ -z "$x" ]; then
-    rc_args="$(get_rcfile_section "$r" "$n" | xargs getopt -s sh -o '' --)"
-    parse_rcfile_args "$rc_args" || exit $?
-    find_expr="$rest_args"
+if [ -z "$origin" -a -z "$destdir" -a -z "$noconf" ]; then
+    # set parameters using args from config file
+    args="$(conf "$name" | xargs getopt -n "$progname" -s sh -o $opts -l $longopts -- -n "$name")" || exit
+    set_pars "$args" || exit
+    eval set -- "$restargs"
+    shift
 fi
 
-# parse command line again in order to override parameters from rcfile
-parse_command_line_args "$cl_args" || exit $(($?-1))
-find_expr="$find_args $rest_args"
+[ -z "$origin" ] && { error "origin path required"; exit 1; }
+[ -z "$destdir" ] && { error "destination path required"; exit 1; }
 
-# set positional arguments
-eval set -- $find_expr
+# printf "help: %s\n" "$help"
+# printf "origin: %s\n" "$origin"
+# printf "destdir: %s\n" "$destdir"
+# printf "noconf: %s\n" "$noconf"
+# printf "name: %s\n" "$name"
+# printf "other args --\n"
+# printf "%s\n" "$@"
 
-# printf "i='%s'\n" "$i"		# input directory
-# printf "o='%s'\n" "$o"		# output directory
-# printf "r='%s'\n" "$r"		# rcfile
-# printf "x='%s'\n" "$x"		# 
-# printf "n='%s'\n" "$n"		# name
-# printf "positional arguments\n"
-# printf "%s\n" "$@"		# find arguments expressions
+[ -d "$destdir" ] || { error "no such directory"; exit 1; }
 
-test -z "$i" && { error "required argument missing -- 'i'"; exit 1; }
-test -z "$o" && { error "required argument missing -- 'o'"; exit 1; }
-test -d "$i" || { error "no such directory -- '$i'"; exit 1; }
-test -d "$o" || { error "no such directory -- '$o'"; exit 1; }
+filenames="$(tempfile)" || exit
+filesizes="$(tempfile)" || exit
 
-o="$(dirname "$o")/$(basename "$o")"
-previous_backup="$(find_previous_backup "$n" "$o")" || exit $?
-previous_backup="${previous_backup:+$o/$previous_backup}"
-output_file="$o/$(current_backup "$n" "$previous_backup").gz"
-
-test -n "$previous_backup" && previous=true
-test -e "$output_file" && overwrite=true
-
-run_find "$i" "$previous_backup" "$@" || exit $?
-if ! [ $? -eq 0 ]; then
-    error "find exited with non-zero status"
-    cleanup
-    exit 1
+prev="$(cd "$destdir" && ls "${name}".* 2> /dev/null \
+	| sort -V | tail -n 1)"
+prevver="$(printf "%s\n" "$prev" | sed 's/.*\.\([0-9][0-9]*\)\.tar.*/\1/')"
+if [ "$prevver" -eq "$prevver" ] 2> /dev/null ; then
+    currver=$(($prevver+1))
+    find "$origin" -newer "${destdir}/$prev" "$@" \
+	 -fprint0 "$filenames" -printf "%s\n" > "$filesizes"
+else
+    currver=0
+    find "$origin" "$@" -fprint0 "$filenames" -printf "%s\n" > "$filesizes"
+fi
+status=$?
+if [ $status -ne 0 ]; then
+   error "find exited with non-zero status: $status"
+   exit $status
 fi
 
-file_count=$(wc -l < "$sizes")
-if [ $file_count -eq 0 ]; then
-    printf "nothing to back up\n"
-    cleanup
-    exit 0
-fi
+originsize="$(awk -v x=0 '/./ {x=x+$1} END {print x}' < "$filesizes")"
+availspace="$(df -P "$destdir"| tail -n 1 | tr -s ' '| cut -d ' ' -f 4)"
+outputfile="${destdir}/${name}.${currver}.tar.gz"
 
-backup_size=$(sum < "$sizes")
-
-if [ -n "$previous_backup" ]; then
+if [ "$currver" -gt 0 ]; then
     printf "previous backup found\n"
 else
     printf "no previous backup found\n"
 fi
+
 printf '%d file(s) (%s) will be backed up\n' \
-    $file_count $(human_readable $backup_size)
-printf "output file is: '%s'\n" "$(basename $output_file)"
-if [ -n "$overwrite" ]; then
-    printf "output file exists -- will be OVERWRITTEN!\n"
+    $(wc -l < "$filesizes") $(human_friendly_units $originsize)
+
+printf "output file is: '%s'\n" "$(basename $outputfile)"
+if [ -e "$outputfile" ]; then
+    printf "output file already exists -- it will be OVERWRITTEN\n"
 fi
-printf "output directory is: '%s'\n" "$(dirname "$output_file")"
+
+printf "output directory is: '%s'\n" "$destdir"
 printf "%s available in output directory\n" \
-    $(human_readable $(free_space $(dirname "$output_file")))
+       "$(human_friendly_units "$availspace")"
 
 REPLY=
 printf '\n'
 while [ "$REPLY" != "y" ]; do
     ask 'proceed?' 'y=yes|n=no|v=view files'
     case "$REPLY" in
-	v) tr '\0' '\n' < "$files" | less ;;
-	n) cleanup; exit 0
+	v) tr '\0' '\n' < "$filenames" | less ;;
+	n) exit 0
     esac
 done
 
 # run_tar
-tar --file "$output_file" --null --files-from "$files" --create \
+tar --file "$outputfile" --null --files-from "$filenames" --create \
     --no-recursion --preserve-permissions --totals --gzip
-if [ $? -ne 0 ]; then
-    printf "tar exited with non-zero status.\n"
+status=$?
+if [ $status -ne 0 ]; then
+    error "tar exited with non-zero status: $status"
+    exit $status
 fi
-cleanup
 printf "bye.\n"
