Use variable $progname instead of $0.

diff --git a/src/fs-lint b/src/fs-lint
--- a/src/fs-lint
+++ b/src/fs-lint
@@ -1,9 +1,11 @@
 #!/bin/sh
 # Search file system for possible rubbish.
 
+progname="$(basename "$0")"
+
 usage () {
     cat <<EOF
-Usage: $0 [OPTIONS] [--] [PATH [PATH...]]
+Usage: $progname [OPTIONS] [--] [PATH [PATH...]]
 Search file system for possible rubbish.
 
 Options (at least one required):
@@ -20,14 +22,14 @@ Other options:
  -d, --delete     delete the files found
      --help       show this help
 
-$0 uses GNU find extensions.
+$progname uses GNU find extensions.
 
 EOF
 }
 
 error () {
     # print $1 to stderr
-    printf "%s\n" "$1" 1>&2
+    printf -- "$progname: %s\n" "$1" 1>&2
 }
 
 confirm_yes_no () {
@@ -97,7 +99,7 @@ fi
 opts=rdhsegbl
 long_opts=recursive,delete,hidden,links,empty,large,backup,latex,help
 
-args="$(LC_ALL=C getopt -n "$0" -s sh -o $opts -l $long_opts -- "$@")"
+args="$(LC_ALL=C getopt -n "$progname" -s sh -o $opts -l $long_opts -- "$@")"
 if [ $? -eq 0 ]; then
     eval set -- "$args"
 else
@@ -134,12 +136,12 @@ while [ $# -gt 0 ]; do
 done
 
 if [ -z "$actions" ]; then
-    error "$0: required option missing"
+    error "required option missing"
     exit 1
 fi
 
 if [ $# -lt 1 ]; then
-    error "$0: required non-option argument missing"
+    error "required non-option argument missing"
     exit 1
 fi
 
diff --git a/src/play-stream b/src/play-stream
--- a/src/play-stream
+++ b/src/play-stream
@@ -1,11 +1,13 @@
 #!/bin/sh
 # Play media streams with mplayer.
 
+progname="$(basename "$0")"
+
 RCFILE="$HOME/.config/streams"
 
 usage () {
     cat <<EOF
-Usage: $0 [OPTIONS] [--] STREAM [MPLAYER_OPTIONS]
+Usage: $progname [OPTIONS] [--] STREAM [MPLAYER_OPTIONS]
 Play media streams with mplayer.
 
 Options:
@@ -22,7 +24,7 @@ EOF
 
 error () {
     # print $1 to stderr
-    printf '%s\n' "$1" 1>&2
+    printf -- "$progname: %s\n" "$1" 1>&2
 }
 
 read_rcfile () {
@@ -68,7 +70,7 @@ fi
 
 short_opts=l
 long_opts=list,help
-args="$(LC_ALL=C getopt -n "$0" -s sh -o $short_opts -l $long_opts -- "$@")"
+args="$(LC_ALL=C getopt -n "$progname" -s sh -o $short_opts -l $long_opts -- "$@")"
 if [ $? -eq 0 ]; then
     eval set -- "$args"
 else
@@ -92,7 +94,7 @@ while [ $# -gt 0 ]; do
 done
 
 if [ $# -lt 1 ]; then
-    error "$0: non-option argument required"
+    error "non-option argument required"
     exit 1
 fi
 stream_name="$1"
@@ -101,7 +103,7 @@ shift
 # get uri
 uri="$(stream_uri "$stream_name")"
 if [ -z "$uri" ]; then
-    error "$0: unknown stream: $1"
+    error "unknown stream: $1"
     exit 1
 fi
 
